plt.figure(figsize=(10, 6))
plt.plot(daily_sales['datum'], daily_sales['Total Daily Sales'], label="Daily Sales", color='blue')
plt.xlabel("Date")
plt.ylabel("Sales")
plt.title("Daily Sales Trend")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
-----------------------------------------
plt.figure(figsize=(10, 6))
plt.plot(weekly_sales['datum'], weekly_sales['Total Weekly Sales'], label="Weekly Sales", color='green')
plt.xlabel("Date")
plt.ylabel("Sales")
plt.title("Weekly Sales Trend")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
-----------------------------------------
plt.figure(figsize=(10, 6))
plt.plot(monthly_sales['datum'], monthly_sales['Total Monthly Sales'], label="Monthly Sales", color='red')
plt.xlabel("Date")
plt.ylabel("Sales")
plt.title("Monthly Sales Trend")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
----------------------------------------
fig, ax1 = plt.subplots(figsize=(10, 6))
ax1.bar(monthly_sales['datum'], monthly_sales['Total Monthly Sales'], color='purple', alpha=0.7, label="Monthly Sales")
ax1.set_xlabel("Date")
ax1.set_ylabel("Monthly Sales", color='purple')
ax1.tick_params(axis='y', labelcolor='purple')
ax2 = ax1.twinx()
ax2.plot(monthly_sales['datum'], monthly_sales['Monthly Growth'], color='orange', label="Monthly Growth")
ax2.set_ylabel("Growth (%)", color='orange')
ax2.tick_params(axis='y', labelcolor='orange')

fig.suptitle("Monthly Sales and Growth Trend")
fig.tight_layout()
plt.grid(True)
plt.show()
---------------------------------------